name: openapi_mock_cli
description: CLI for resolving OpenAPI example responses via openapi_mock.
version: 0.0.1
repository: https://github.com/hiromu-kon/openapi_mock/tree/main/packages/openapi_mock_cli
homepage: https://github.com/hiromu-kon/openapi_mock

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  args: ^2.5.0
  openapi_mock: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  openapi_mock_cli: openapi_mock_cli
