name: openapi_mock
description: OpenAPI-driven mock engine for Dart and Flutter clients.
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  http: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
