name: openapi_mock
description: Core OpenAPI-driven mock engine for Dart and Flutter.
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
