name: openapi_mock_server
description: Local mock server adapter for openapi_mock.
version: 0.0.1
repository: https://github.com/hiromu-kon/openapi_mock/tree/main/packages/openapi_mock_server
homepage: https://github.com/hiromu-kon/openapi_mock

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  openapi_mock: ^0.0.1

dev_dependencies:
  lints: ">=2.0.0 <7.0.0"
  test: ^1.21.0
