name: openapi_mock_http
description: HTTP adapter for openapi_mock.
version: 0.0.1
repository: https://github.com/hiromu-kon/openapi_mock/tree/main/packages/openapi_mock_http
homepage: https://github.com/hiromu-kon/openapi_mock

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  http: ^1.1.0
  openapi_mock: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
